import test from 'node:test';
import assert from 'node:assert/strict';
import {storage,migrate} from './helpers/storage.mjs';
import {weekStart,itemDefinition,qualityBand} from '../server/catalog.mjs';
import {ForestRoom,availableRooms,publicRooms} from '../server/room.mjs';
import {World,createPlayer} from '../dist/engine.js';
async function setup(t){const s=storage();migrate(s);t.after(()=>s.sqlite.close());for(const id of ['alice','bob'])await s.call('register',{id,username:id,displayName:id,passwordHash:'unused'});return s;}
const clear=(round,id='alice',hero='kael',extra={})=>({round,chapter:1,mode:'solo',duration:60,outcome:'won',finishedAt:Date.now(),players:[{id,hero,name:id,loot:'kael_head_1'}],kills:[{id:1,kind:'forest_dragon'},{id:2,kind:'boss'}],...extra});
const hero=async(s,id='alice',h='kael')=>(await s.call('game-profile',{id})).heroes.find(x=>x.id===h);
async function unlockAlchemy(s){s.sqlite.prepare("UPDATE accounts SET gold=1000 WHERE id='alice'").run();await s.call('profession-unlock',{id:'alice',profession:'alchemy'});const h=await hero(s);await s.call('recipe-learn',{id:'alice',hero:'kael',item:h.inventory.find(i=>i.catalog_id==='recipe_healing_potion').id});}
test('profession purchase, recipe learning, materials and crafting are atomic and hero scoped',async t=>{
 const s=await setup(t);await s.call('settle',clear('a'));await assert.rejects(()=>s.call('profession-unlock',{id:'alice',profession:'alchemy'}),/100 gold/);await unlockAlchemy(s);await s.call('profession-unlock',{id:'alice',profession:'alchemy'});assert.equal((await s.call('game-profile',{id:'alice'})).gold,900);
 await assert.rejects(()=>s.call('craft',{id:'alice',hero:'lyra',recipe:'healing_potion'}),/materiais/);
 const r=await Promise.allSettled([1,2].map(()=>s.call('craft',{id:'alice',hero:'kael',recipe:'healing_potion'})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const h=await hero(s);assert.equal(h.inventory.filter(i=>i.catalog_id==='healing_potion').length,1);assert.equal(h.inventory.filter(i=>i.catalog_id==='forest_herb').length,0);assert.equal(h.inventory.filter(i=>i.catalog_id==='recipe_healing_potion').length,0);assert.equal((await hero(s,'alice','lyra')).inventory.length,0);
 assert.ok((await s.call('game-profile',{id:'alice'})).achievements.some(a=>a.hero==='account'&&a.achievement==='artisan'));
});
test('consumable slots enforce ownership and potion cooldown survives repeat and concurrent requests',async t=>{
 const s=await setup(t);await s.call('settle',clear('a'));await s.call('settle',clear('b'));await unlockAlchemy(s);for(let i=0;i<2;i++)await s.call('craft',{id:'alice',hero:'kael',recipe:'healing_potion'});
 await assert.rejects(()=>s.call('hotbar-set',{id:'alice',hero:'lyra',slot:1,catalog:'healing_potion'}));await s.call('hotbar-set',{id:'alice',hero:'kael',slot:1,catalog:'healing_potion'});
 const result=await Promise.all([1,2].map(i=>s.call('potion-use',{id:'alice',hero:'kael',slot:1,useId:'use'+i})));assert.equal(result.filter(r=>r.consumed).length,1);assert.equal(result[0].healFraction,.2);assert.equal((await hero(s)).inventory.filter(i=>i.catalog_id==='healing_potion').length,1);
 s.sqlite.prepare('UPDATE potion_cooldowns SET until=0').run();assert.equal((await s.call('potion-use',{id:'alice',hero:'kael',slot:1,useId:'use1'})).consumed,false);assert.equal((await s.call('potion-use',{id:'alice',hero:'kael',slot:1,useId:'use3'})).consumed,true);assert.equal((await hero(s)).inventory.filter(i=>i.catalog_id==='healing_potion').length,0);
});
test('sale proceeds remain in owner mail until collected exactly once and welcome mail is automatic',async t=>{
 const s=await setup(t);assert.equal((await s.call('mail-list',{id:'alice'})).messages.length,1);await s.call('settle',clear('a'));const item=(await hero(s)).inventory.find(i=>i.slot==='head');s.sqlite.prepare("UPDATE accounts SET gold=100 WHERE id='bob'").run();await s.call('market-sell',{id:'alice',item:item.id,price:40});const listing=(await s.call('market-list',{id:'bob'})).listings[0];assert.equal((await s.call('market-list',{id:'alice'})).listings.length,0);assert.equal((await s.call('market-list',{id:'alice',mine:'1'})).listings.length,1);await s.call('market-buy',{id:'bob',hero:'lyra',listing:listing.id});assert.equal((await s.call('game-profile',{id:'alice'})).gold,80);const mail=(await s.call('mail-list',{id:'alice'})).messages.find(m=>m.gold===40);await s.call('mail-claim',{id:'bob',mail:mail.id});assert.equal((await s.call('game-profile',{id:'bob'})).gold,60);
 await Promise.all([s.call('mail-claim',{id:'alice',mail:mail.id}),s.call('mail-claim',{id:'alice',all:true})]);assert.equal((await s.call('game-profile',{id:'alice'})).gold,120);assert.equal((await s.call('game-profile',{id:'alice'})).unreadMail,0);
});
test('only activated leader key breaks; refarming requires a new normal clear and never overwrites valid keys',async t=>{
 const s=await setup(t);await s.call('settle',clear('old'));await s.call('settle',clear('guest','bob'));await s.call('key-activate',{id:'alice',hero:'kael',chapter:1,round:'m1'});await s.call('key-resolve',{round:'m1',success:true,upgrade:3});await s.call('settle',clear('normal-with-valid'));assert.equal((await hero(s)).keys[0].level,5);
 await s.call('key-activate',{id:'alice',hero:'kael',chapter:1,round:'m2'});await s.call('key-resolve',{round:'m2',success:false});assert.equal((await hero(s,'bob')).keys[0].status,'available');assert.equal((await hero(s)).keys[0].status,'broken');await assert.rejects(()=>s.call('weekly-claim',{id:'alice',hero:'kael'}),/chave válida/);
 await s.call('settle',clear('old'));assert.equal((await hero(s)).keys[0].status,'broken');await s.call('settle',clear('refarm'));assert.equal((await hero(s)).keys[0].level,2);assert.equal((await hero(s)).keys[0].status,'available');
});
test('weekly chest is once per hero per week with valid keys, scaled stats and preserved item quality',async t=>{
 const s=await setup(t);await s.call('settle',clear('a'));await assert.rejects(()=>s.call('weekly-claim',{id:'alice',hero:'kael'}),/semana anterior/);s.sqlite.prepare('UPDATE mythic_keys SET level=20,week=?').run(weekStart()-7*86400000);const r=await Promise.allSettled([1,2].map(()=>s.call('weekly-claim',{id:'alice',hero:'kael'})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);const item=(await hero(s)).inventory.find(i=>i.quality===3);assert.ok(item);assert.equal(item.definition.hero,'kael');assert.deepEqual([9,10,14,15,19,20,99].map(qualityBand),[0,1,1,2,2,3,3]);assert.ok(itemDefinition({catalog_id:'kael_weapon_1',quality:3}).attributes.damage>itemDefinition({catalog_id:'kael_weapon_1'}).attributes.damage);
 await assert.rejects(()=>s.call('weekly-claim',{id:'alice',hero:'lyra'}));s.sqlite.prepare('UPDATE weekly_claims SET week=?').run(weekStart()-7*86400000);await s.call('weekly-claim',{id:'alice',hero:'kael'});assert.equal((await hero(s)).inventory.filter(i=>i.quality===3).length,2);
 await s.call('settle',clear('mythic','bob','lyra',{mythic:{level:15}}));assert.equal((await hero(s,'bob','lyra')).inventory.find(i=>i.slot==='head').quality,2);
});
test('clan bank has sequential paid tabs and atomic deposits, withdrawals and listing isolation',async t=>{
 const s=await setup(t);s.sqlite.prepare("UPDATE accounts SET gold=10000 WHERE id='alice'").run();await s.call('clan-create',{id:'alice',name:'Astral'});const c=(await s.call('clan-view',{id:'alice'})).clan.clan_id;await s.call('clan-invite',{id:'alice',username:'bob'});await s.call('clan-accept-invite',{id:'bob',clan:c});assert.equal((await s.call('bank-view',{id:'alice'})).tabs.length,4);await assert.rejects(()=>s.call('bank-unlock',{id:'bob',tab:5}));await assert.rejects(()=>s.call('bank-unlock',{id:'alice',tab:6}));const r=await Promise.allSettled([1,2].map(()=>s.call('bank-unlock',{id:'alice',tab:5})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal((await s.call('game-profile',{id:'alice'})).gold,8500);await s.call('bank-unlock',{id:'alice',tab:6});assert.equal((await s.call('game-profile',{id:'alice'})).gold,7500);await s.call('bank-rename',{id:'alice',tab:5,name:'Poções'});
 await s.call('settle',clear('drop'));const item=(await hero(s)).inventory.find(i=>i.slot==='head');await s.call('equip',{id:'alice',hero:'kael',item:item.id,equip:true});await assert.rejects(()=>s.call('bank-deposit',{id:'alice',item:item.id,tab:1}));await s.call('equip',{id:'alice',hero:'kael',item:item.id,equip:false});await s.call('bank-deposit',{id:'alice',item:item.id,tab:5});assert.ok(!(await hero(s)).inventory.some(i=>i.id===item.id));await assert.rejects(()=>s.call('market-sell',{id:'alice',item:item.id,price:1}));await assert.rejects(()=>s.call('equip',{id:'alice',hero:'kael',item:item.id,equip:true}));
 const withdrawals=await Promise.allSettled(['alice','bob'].map(id=>s.call('bank-withdraw',{id,hero:'lyra',item:item.id})));assert.equal(withdrawals.filter(r=>r.status==='fulfilled').length,1);assert.equal((await s.call('bank-view',{id:'bob'})).items.length,0);assert.equal((await hero(s,'alice','lyra')).inventory[0].id,item.id);
 await s.call('bank-deposit',{id:'alice',item:item.id,tab:1});await s.call('clan-delete',{id:'alice'});assert.ok((await hero(s,'alice','lyra')).inventory.some(i=>i.id===item.id));
});
test('hero achievements count unique dragon kills, titles respect ownership and skin purchases debit once',async t=>{
 const s=await setup(t);const p=clear('dragons');p.kills=Array.from({length:5},(_,i)=>({id:i,kind:'forest_dragon'}));await s.call('rewards',p);await s.call('rewards',p);const a=await s.call('game-profile',{id:'alice'});assert.equal(a.achievements.filter(x=>x.achievement==='dragon_hunter').length,1);await s.call('title-set',{id:'alice',hero:'kael',title:'dragon_hunter'});await assert.rejects(()=>s.call('title-set',{id:'alice',hero:'lyra',title:'dragon_hunter'}));await assert.rejects(()=>s.call('skin-set',{id:'alice',hero:'kael',skin:'kael_astral'}));s.sqlite.prepare("UPDATE accounts SET gems=10 WHERE id='alice'").run();await Promise.all([1,2].map(()=>s.call('skin-buy',{id:'alice',skin:'kael_astral'})));assert.equal((await s.call('game-profile',{id:'alice'})).gems,0);await s.call('skin-set',{id:'alice',hero:'kael',skin:'kael_astral'});await assert.rejects(()=>s.call('skin-set',{id:'alice',hero:'lyra',skin:'kael_astral'}));assert.equal((await hero(s)).skin,'kael_astral');await s.call('skin-set',{id:'alice',hero:'kael',skin:'default'});
});
test('public browser excludes private, full, started, PvP and locked chapters',()=>{
 const r={visible:true,mode:'coop',stage:'lobby',members:new Map([['a',{name:'Alice'}]]),host:'a',maxClients:4,chapter:2,roomId:'PUBLIC',lobby:()=>({useKey:true,key:{status:'available',level:12}})};publicRooms.set('test',r);try{assert.equal(availableRooms(0,1).length,0);assert.equal(availableRooms(1,3).length,0);assert.equal(availableRooms(2,3)[0].mythicLevel,12);for(const [field,value] of [['visible',false],['mode','pvp'],['stage','playing'],['maxClients',1]]){const old=r[field];r[field]=value;assert.equal(availableRooms(0,3).length,0);r[field]=old;}}finally{publicRooms.delete('test');}
});
test('room potion applies bounded heal only during active combat and never accepts HP from client',async()=>{
 const room=new ForestRoom();room.world=new World();room.world.enemies=[];room.world.players=[createPlayer('a')];room.world.player=room.world.players[0];room.world.start();room.world.player.hp=50;room.stage='playing';room.members.set('a',{accountId:'alice',hero:'kael',connected:true,paused:false});let calls=0;room.accounts={store:{call:async()=>{calls++;return {consumed:true,healFraction:.2,cooldownUntil:Date.now()+30000}}}};const c={sessionId:'a',send(){}};await room.usePotion(c,1);assert.equal(room.world.player.hp,70);await room.usePotion(c,1);assert.equal(calls,1);room.members.get('a').potionUntil=0;room.members.get('a').paused=true;await room.usePotion(c,1);assert.equal(calls,1);room.clock.clear();
});
test('real public lobby supports discovery, host-only kick and timeout breaks only the leader key',{timeout:12000},async t=>{
 const {Accounts}=await import('../server/accounts.mjs'),{startServer}=await import('../server/main.mjs'),{Client}=await import('@colyseus/sdk'),{matchMaker}=await import('@colyseus/core');const s=storage();migrate(s);for(const id of ['alice','bob']){await s.call('register',{id,username:id,displayName:id,passwordHash:'unused'});await s.call('settle',clear('unlock-'+id,id));}const accounts=new Accounts(s,'test'),server=await startServer(2593,{accounts});const clients=[];t.after(async()=>{await Promise.allSettled(clients.map(c=>Promise.race([c.leave(),new Promise(r=>setTimeout(r,250))])));await server.gracefullyShutdown(false);s.sqlite.close();});const ta=await accounts.createSession('alice'),tb=await accounts.createSession('bob'),sdk=new Client('http://127.0.0.1:2593');const host=await sdk.create('forest',{mode:'coop',chapter:1,hero:'kael',ticket:accounts.ticket(ta)});clients.push(host);host.onMessage('*',()=>{});let guest=await sdk.joinById(host.roomId,{hero:'kael',ticket:accounts.ticket(tb)});clients.push(guest);guest.onMessage('*',()=>{});const room=matchMaker.getLocalRoomById(host.roomId),until=async fn=>{const end=Date.now()+4000;while(!fn()){if(Date.now()>end)assert.fail('Timed out');await new Promise(r=>setTimeout(r,20));}};
 host.send('visibility',true);await until(()=>room.visible);const response=await fetch('http://127.0.0.1:2593/api/game/rooms?hero=kael',{headers:{cookie:'emberfall_session='+ta}});assert.equal(response.status,200);assert.equal((await response.json()).rooms[0].code,host.roomId);guest.send('kick',host.sessionId);await new Promise(r=>setTimeout(r,50));assert.equal(room.members.size,2);host.send('kick',guest.sessionId);await until(()=>room.members.size===1);guest=await sdk.joinById(host.roomId,{hero:'kael',ticket:accounts.ticket(tb)});clients.push(guest);guest.onMessage('*',()=>{});host.send('key',true);await until(()=>room.useKey);host.send('ready',true);guest.send('ready',true);await until(()=>[...room.members.values()].every(m=>m.ready));host.send('start');await until(()=>room.stage==='countdown');room.countdownAt=Date.now()-1;await until(()=>room.stage==='playing');assert.equal(availableRooms(0,3).length,0);for(const p of room.world.players){room.world.player=p;p.invincible=0;room.world.damagePlayer(100000,p.x);}assert.equal(room.world.status,'playing');room.mythic.deadline=Date.now()-1;await until(()=>room.progress==='saved');assert.equal((await hero(s)).keys[0].status,'broken');assert.equal((await hero(s,'bob')).keys[0].status,'available');assert.equal(room.world.status,'dead');
});
