import test from 'node:test';
import assert from 'node:assert/strict';
import {World,platforms} from '../dist/engine.js';
const step=(w,seconds,input={})=>{for(let i=0;i<seconds*120;i++)w.update(1/120,input);};
const empty=()=>{const w=new World();w.start();w.enemies=[];return w;};

test('player rests on ground and moves at bounded speed',()=>{const w=empty();step(w,1);assert.equal(w.player.y,615);step(w,1,{right:true});assert.ok(w.player.x>440);assert.ok(w.player.vx<=290);});
test('double jump is limited to two airborne jumps and resets on landing',()=>{const w=empty();w.action('jump');assert.equal(w.player.jumps,1);step(w,.1);w.action('jump');assert.equal(w.player.jumps,2);step(w,.05);const vy=w.player.vy;w.action('jump');assert.equal(w.player.vy,vy);step(w,1.5);assert.equal(w.player.jumps,0);assert.equal(w.player.y,615);});
test('one-way platform allows ascending and catches descending feet',()=>{const w=empty();w.player.x=600;w.action('jump');w.player.vy=-640;step(w,.8);assert.equal(w.player.y,505);assert.equal(w.player.grounded,true);});
test('attack respects facing and cooldown, then chains combo',()=>{const w=new World();w.start();w.player.x=700;const e=w.enemies[0];w.player.dir=-1;w.action('attack');assert.equal(e.hp,e.maxHp);step(w,.3);w.player.dir=1;w.action('attack');const hp=e.hp;assert.ok(hp<e.maxHp);w.action('attack');assert.equal(e.hp,hp);step(w,.3);w.action('attack');assert.ok(e.hp<hp);});
test('dash prevents damage and cannot be spammed',()=>{const w=empty();w.action('dash');w.damagePlayer(50,0);assert.equal(w.player.hp,100);const cd=w.player.dashCooldown;w.action('dash');assert.equal(w.player.dashCooldown,cd);step(w,.5);w.damagePlayer(12,0);assert.equal(w.player.hp,88);});
test('nova hits nearby enemies once and respects cooldown',()=>{const w=new World();w.start();w.player.x=700;w.action('skill2');assert.equal(w.enemies[0].dead,true);assert.equal(w.player.skill2,10);w.action('skill2');assert.equal(w.player.skill2,10);assert.equal(w.kills,1);});
test('solar projectile pierces without repeatedly damaging same enemy',()=>{const w=new World();w.start();w.player.x=700;w.action('skill1');step(w,.15);assert.equal(w.enemies[0].dead,true);assert.equal(w.kills,1);assert.ok(w.player.skill1>4);});
test('fall costs health and returns to checkpoint',()=>{const w=empty();w.player.x=1200;w.player.y=851;step(w,1/120);assert.equal(w.player.hp,84);assert.equal(w.player.x,190);assert.ok(w.player.y<615);});
test('boss encounter heals player and closes arena',()=>{const w=new World();w.start();w.player.hp=40;w.player.x=3900;step(w,.02);assert.equal(w.bossActive,true);assert.equal(w.player.hp,75);w.player.x=3700;step(w,.02);assert.equal(w.player.x,3850);});
test('boss has telegraphed slam and ranged patterns',()=>{const w=new World();w.start();w.player.x=3900;w.player.invincible=100;step(w,8);assert.ok(w.enemies.at(-1).phase>=2);assert.ok(w.events.some(e=>e.type==='warning'&&e.kind==='slam'));assert.ok(w.events.some(e=>e.type==='warning'&&e.kind==='shot'));});
test('defeating boss through attacks produces victory',()=>{const w=new World();w.start();w.player.x=4290;w.player.invincible=100;w.player.dir=1;const boss=w.enemies.at(-1);step(w,8,{attack:true});assert.equal(boss.dead,true);assert.equal(w.status,'won');assert.equal(w.events.filter(e=>e.type==='won').length,1);});
test('chapter death respawns at checkpoint without resetting enemies or elapsed time',()=>{const w=new World();w.enemies=[];w.start();w.player.checkpoint=1700;w.damagePlayer(100,0);assert.equal(w.status,'playing');assert.equal(w.player.hp,0);step(w,1,{right:true});assert.equal(w.player.hp,0);step(w,2.2);assert.equal(w.player.hp,100);assert.equal(w.player.x,1700);assert.ok(w.elapsed>=3);assert.ok(w.player.invincible>0);});
test('entire level is traversable using movement, jumps and dash',()=>{const w=empty();w.player.invincible=1000;let nextJump=0,second=0,lastJ=0;for(let i=0;i<120*35;i++){const p=w.player;const actions=[];if(p.grounded&&w.time>nextJump){actions.push('jump');second=w.time+.3;nextJump=w.time+.9;lastJ=w.time;}if(!p.grounded&&p.jumps===1&&w.time>second){actions.push('jump');second=Infinity;}if(!p.grounded&&p.jumps===2&&p.vy>30&&p.dashCooldown<=0)actions.push('dash');w.update(1/120,{right:true,actions});if(p.x>4500)break;}assert.ok(w.player.x>4500,`Reached only ${w.player.x}`);assert.equal(w.player.hp,100);});
