import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {storage,migrate} from './helpers/storage.mjs';
import {weekStart} from '../server/catalog.mjs';
import {mythicRules,mythicUpgrade} from '../server/mythic.mjs';
import {validSignature,verifiedPayment} from '../server/payments.mjs';
import {ForestRoom} from '../server/room.mjs';
import {World} from '../dist/engine.js';
async function setup(t){const s=storage();migrate(s);t.after(()=>s.sqlite.close());for(const id of ['alice','bob','carol'])await s.call('register',{id,username:id,displayName:id,passwordHash:'unused'});return s;}
const clear=(round,id='alice',hero='kael',extra={})=>({round,chapter:1,mode:'solo',duration:60,outcome:'won',finishedAt:Date.now(),players:[{id,hero,name:id,loot:'kael_head_1'}],kills:[{id:1,kind:'goblin'},{id:2,kind:'boss'}],...extra});
test('chapters and exclusive weekly keys belong to the hero; broken keys can be refarmed without replacing valid keys',async t=>{
 const s=await setup(t);await s.call('settle',clear('normal'));await s.call('settle',clear('normal-again'));let p=await s.call('game-profile',{id:'alice'});assert.equal(p.heroes[0].unlockedChapter,2);assert.equal(p.heroes[1].unlockedChapter,1);assert.equal(p.heroes[0].keys.length,1);
 const r=await Promise.allSettled(['a','b'].map(round=>s.call('key-activate',{id:'alice',hero:'kael',chapter:1,round})));assert.equal(r.filter(x=>x.status==='fulfilled').length,1);await assert.rejects(()=>s.call('key-activate',{id:'alice',hero:'lyra',chapter:1,round:'wrong'}));
 for(let i=0;i<2;i++)await s.call('key-resolve',{round:'a',success:true,upgrade:3});assert.equal((await s.call('game-profile',{id:'alice'})).heroes[0].keys[0].level,5);await s.call('key-activate',{id:'alice',hero:'kael',chapter:1,round:'c'});await s.call('key-resolve',{round:'c',success:false});await s.call('settle',clear('refarm'));assert.equal((await s.call('game-profile',{id:'alice'})).heroes[0].keys[0].status,'available');
 s.sqlite.prepare('UPDATE mythic_keys SET week=?').run(weekStart()-7*86400000);assert.equal((await s.call('game-profile',{id:'alice'})).heroes[0].keys.length,0);await s.call('settle',clear('new-week'));assert.equal((await s.call('game-profile',{id:'alice'})).heroes[0].keys[0].level,2);
});
test('PvP awards only rank and history, never currencies, XP, items, progress or keys',async t=>{
 const s=await setup(t);await s.call('settle',clear('pvp','alice','lyra',{mode:'pvp',chapter:3,winner:'alice',reason:'knockout'}));const p=await s.call('game-profile',{id:'alice'});assert.equal(p.gold,0);assert.equal(p.gems,0);assert.ok(p.heroes.every(h=>h.totalXp===0&&h.inventory.length===0&&h.unlockedChapter===1&&h.keys.length===0));assert.equal((await s.call('ranking',{mode:'pvp'})).entries[0].kills,1);
});
test('mythic thresholds, damage scaling and timeout during pause',()=>{
 const r=mythicRules(1,2);assert.equal(mythicUpgrade(r.limitMs*.59,r.limitMs,19,20),3);assert.equal(mythicUpgrade(r.limitMs*.75,r.limitMs,18,20),1);assert.equal(mythicUpgrade(r.limitMs*.9,r.limitMs,19,20),1);assert.equal(mythicUpgrade(r.limitMs*.9,r.limitMs,18,20),0);assert.equal(mythicUpgrade(r.limitMs,r.limitMs,20,20),null);
 const w=new World();w.start();w.enemyDamageScale=r.damage;w.damagePlayer(20,0);assert.equal(w.player.hp,100-Math.round(20*r.damage));const room=new ForestRoom();room.world=w;room.stage='playing';room.round=1;room.mythic={...r,deadline:Date.now()-1,startedAt:Date.now()-r.limitMs-1,total:20};room.members=new Map([['a',{paused:true,connected:true}]]);let result;room.recordResult=reason=>{if(reason)result=reason;};room.advance(16);assert.equal(w.status,'dead');assert.equal(result,'timeout');room.clock.clear();
});
test('mythic ranking is separate and prioritizes level before time',async t=>{
 const s=await setup(t);await s.call('settle',clear('normal'));await s.call('settle',clear('m2','alice','kael',{mythic:{level:2},duration:40}));await s.call('settle',clear('m5','alice','kael',{mythic:{level:5},duration:150}));assert.equal((await s.call('ranking',{mode:'solo'})).entries[0].id,'normal');assert.equal((await s.call('ranking',{mode:'solo',mythic:'1'})).entries[0].id,'m5');
});
test('clan creation is atomic; authority and membership protect private chat and management',async t=>{
 const s=await setup(t);await assert.rejects(()=>s.call('clan-create',{id:'alice',name:'Aurora'}));s.sqlite.prepare('UPDATE accounts SET gold=2000').run();await Promise.allSettled([s.call('clan-create',{id:'alice',name:'Aurora'}),s.call('clan-create',{id:'alice',name:'Outra'})]);assert.equal((await s.call('game-profile',{id:'alice'})).gold,1000);const c=(await s.call('clan-view',{id:'alice'})).clan.clan_id;
 await s.call('clan-apply',{id:'bob',clan:c});await assert.rejects(()=>s.call('clan-approve',{id:'carol',clan:c,target:'bob'}));await s.call('clan-approve',{id:'alice',target:'bob'});await s.call('chat-send',{id:'bob',channel:'clan',body:'Privado'});assert.equal((await s.call('chat-read',{id:'alice',channel:'clan'})).messages.length,1);assert.equal((await s.call('chat-read',{id:'carol',channel:'global'})).messages.length,0);await assert.rejects(()=>s.call('chat-read',{id:'carol',channel:'clan'}));await assert.rejects(()=>s.call('clan-invite',{id:'bob',username:'carol'}));
 await s.call('clan-role',{id:'alice',target:'bob',role:'admin'});await s.call('clan-invite',{id:'bob',username:'carol'});await s.call('clan-accept-invite',{id:'carol',clan:c});assert.equal((await s.call('clan-view',{id:'alice'})).members.length,3);await assert.rejects(()=>s.call('clan-delete',{id:'bob'}));await s.call('clan-kick',{id:'bob',target:'alice'});assert.ok((await s.call('clan-view',{id:'alice'})).clan);await s.call('clan-kick',{id:'alice',target:'bob'});await assert.rejects(()=>s.call('chat-read',{id:'bob',channel:'clan'}));await s.call('clan-delete',{id:'alice'});assert.equal((await s.call('clan-view',{id:'carol'})).clan,null);assert.equal(s.sqlite.prepare('SELECT COUNT(*) n FROM chat_messages WHERE clan_id=?').get(c).n,0);
});
test('market history is visible only to buyer and seller after ownership transfer',async t=>{
 const s=await setup(t);await s.call('settle',clear('drop'));s.sqlite.prepare("UPDATE accounts SET gold=100 WHERE id='bob'").run();const item=(await s.call('game-profile',{id:'alice'})).heroes[0].inventory[0];await s.call('market-sell',{id:'alice',item:item.id,price:50});const l=(await s.call('market-list',{id:'bob'})).listings[0];await s.call('market-buy',{id:'bob',hero:'lyra',listing:l.id});assert.equal((await s.call('market-history',{id:'alice',side:'sell'})).transactions[0].buyer_name,'bob');assert.equal((await s.call('market-history',{id:'bob',side:'buy'})).transactions[0].seller_name,'alice');assert.equal((await s.call('market-history',{id:'carol'})).transactions.length,0);
});
test('payment signature, exact amount, identity, currency, method and environment are validated',()=>{
 const ts=String(Math.floor(Date.now()/1000)),id='12345',secret='secret',h={'x-request-id':'request'};h['x-signature']=`ts=${ts},v1=${createHmac('sha256',secret).update(`id:${id};request-id:request;ts:${ts};`).digest('hex')}`;assert.ok(validSignature(h,id,secret));assert.equal(validSignature(h,'6789',secret),false);assert.equal(validSignature(h,id,secret,Date.now()+700000),false);
 const order={id:'order',amount_cents:1,live:1},p={id:12345,external_reference:'order',currency_id:'BRL',payment_method_id:'pix',transaction_amount:.01,live_mode:true,date_last_updated:new Date().toISOString(),status:'approved'};assert.equal(verifiedPayment(p,order).amountCents,1);for(const change of [{external_reference:'wrong'},{transaction_amount:.014},{payment_method_id:'visa'},{live_mode:false},{currency_id:'USD'}])assert.throws(()=>verifiedPayment({...p,...change},order));
});
test('premium credit is exactly once; stale events and sandbox cannot mint money; refunds revoke once',async t=>{
 const s=await setup(t),order=randomUUID();await s.call('payment-create',{id:'alice',order,amountCents:1,coins:10,live:true});const u={order,providerId:'1234',amountCents:1,live:true,status:'pending',updatedAt:100};await s.call('payment-update',u);assert.equal((await s.call('game-profile',{id:'alice'})).gems,0);await Promise.all([s.call('payment-update',{...u,status:'approved',updatedAt:200}),s.call('payment-update',{...u,status:'approved',updatedAt:200})]);assert.equal((await s.call('game-profile',{id:'alice'})).gems,10);await s.call('payment-update',u);assert.equal((await s.call('game-profile',{id:'alice'})).gems,10);await assert.rejects(()=>s.call('payment-update',{...u,amountCents:10}));await s.call('payment-update',{...u,status:'refunded',updatedAt:300});await s.call('payment-update',{...u,status:'approved',updatedAt:400});assert.equal((await s.call('game-profile',{id:'alice'})).gems,0);assert.equal(await s.call('payment-get',{id:'bob',order}),null);const sandbox=randomUUID();await s.call('payment-create',{id:'alice',order:sandbox,amountCents:1,coins:10,live:false});await s.call('payment-update',{...u,order:sandbox,providerId:'5678',status:'approved',live:false});assert.equal((await s.call('game-profile',{id:'alice'})).gems,0);
});
test('real solo lobby consumes and upgrades a key, then waits again for explicit start',{timeout:15000},async t=>{
 const {Accounts}=await import('../server/accounts.mjs'),{startServer}=await import('../server/main.mjs'),{Client}=await import('@colyseus/sdk'),{matchMaker}=await import('@colyseus/core');const s=storage();migrate(s);await s.call('register',{id:'alice',username:'alice',displayName:'Alice',passwordHash:'unused'});await s.call('settle',clear('unlock'));const accounts=new Accounts(s,'test'),server=await startServer(2592,{accounts});let c;t.after(async()=>{if(c)await c.leave();await server.gracefullyShutdown(false);s.sqlite.close();});const token=await accounts.createSession('alice');c=await new Client('http://127.0.0.1:2592').create('forest',{mode:'solo',chapter:1,hero:'kael',ticket:accounts.ticket(token)});c.onMessage('*',()=>{});const room=matchMaker.getLocalRoomById(c.roomId);const until=async fn=>{const end=Date.now()+5000;while(!fn()){if(Date.now()>end)assert.fail('Timed out');await new Promise(r=>setTimeout(r,20));}};
 await new Promise(r=>setTimeout(r,100));assert.equal(room.stage,'lobby');c.send('key',true);c.send('ready',true);c.send('start');await until(()=>room.stage==='countdown');assert.equal(room.mythic.level,2);assert.ok(room.world.enemies[0].maxHp>new World().enemies[0].maxHp);room.countdownAt=Date.now()-1;await until(()=>room.world.status==='playing');for(const e of room.world.enemies)e.dead=true;room.world.status='won';await until(()=>room.progress==='saved');assert.equal((await s.call('game-profile',{id:'alice'})).heroes[0].keys[0].level,5);c.send('restart');await until(()=>room.stage==='lobby');assert.equal(room.useKey,false);assert.equal(room.lobby().key.level,5);
});
test('HTTP Pix checkout binds buyer and fixed product; signed webhooks reconcile without a login',{timeout:15000},async t=>{
 const {Accounts}=await import('../server/accounts.mjs'),{startServer}=await import('../server/main.mjs');const s=storage();migrate(s);await s.call('register',{id:'alice',username:'alice',displayName:'Alice',passwordHash:'unused'});const accounts=new Accounts(s,'test'),server=await startServer(2593,{accounts}),original=globalThis.fetch,keys=['MERCADOPAGO_ACCESS_TOKEN','MERCADOPAGO_WEBHOOK_SECRET','PIX_LIVE_MODE'],saved=Object.fromEntries(keys.map(k=>[k,process.env[k]]));t.after(async()=>{globalThis.fetch=original;await server.gracefullyShutdown(false);s.sqlite.close();for(const [k,v] of Object.entries(saved)){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
 const token=await accounts.createSession('alice'),base='http://127.0.0.1:2593';const api=(path,body,auth=true)=>original(base+path,{method:body?'POST':'GET',headers:{...(auth?{Cookie:`emberfall_session=${token}`} :{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});assert.equal((await api('/api/game/shop',null,false)).status,401);process.env.MERCADOPAGO_ACCESS_TOKEN='test-token';process.env.MERCADOPAGO_WEBHOOK_SECRET='test-secret';process.env.PIX_LIVE_MODE='true';
 let payment;globalThis.fetch=async(url,o)=>{if(String(url).startsWith('https://api.mercadopago.com')){if(o.method==='POST'){const b=JSON.parse(o.body);assert.equal(b.transaction_amount,.01);assert.equal(b.payment_method_id,'pix');payment={id:98765,external_reference:b.external_reference,transaction_amount:b.transaction_amount,currency_id:'BRL',payment_method_id:'pix',live_mode:true,status:'pending',date_last_updated:new Date().toISOString(),point_of_interaction:{transaction_data:{qr_code:'TEST-PIX'}}};}return Response.json(payment);}return original(url,o);};
 const order=randomUUID(),r=await api('/api/game/shop/checkout',{order,email:'buyer@example.com',cpf:'12345678901',id:'other',amountCents:10000,coins:99999});assert.equal(r.status,200,await r.clone().text());assert.equal((await r.json()).amountCents,1);assert.equal((await s.call('payment-get',{order})).account_id,'alice');assert.equal((await s.call('game-profile',{id:'alice'})).gems,0);
 payment={...payment,status:'approved',date_last_updated:new Date(Date.now()+1000).toISOString()};const ts=String(Math.floor(Date.now()/1000)),requestId='test-webhook',sig=createHmac('sha256','test-secret').update(`id:98765;request-id:${requestId};ts:${ts};`).digest('hex');for(let i=0;i<2;i++){const r=await original(base+'/payments/mercadopago/webhook?data.id=98765',{method:'POST',headers:{'Content-Type':'application/json','x-request-id':requestId,'x-signature':`ts=${ts},v1=${sig}`},body:JSON.stringify({type:'payment',data:{id:98765}})});assert.equal(r.status,200);}assert.equal((await s.call('game-profile',{id:'alice'})).gems,10);assert.equal((await(await api('/api/game/shop/order/'+order)).json()).granted,10);
});
