import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,primaryKey,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const accounts=sqliteTable('accounts',{
 id:text('id').primaryKey(),username:text('username').notNull().unique(),displayName:text('display_name').notNull(),
 gems:integer('gems').notNull().default(0),gold:integer('gold').notNull().default(0),passwordHash:text('password_hash').notNull(),unlockedChapter:integer('unlocked_chapter').notNull().default(1),
 preferredHero:text('preferred_hero').notNull().default('kael'),createdAt:integer('created_at').notNull()
});
export const sessions=sqliteTable('sessions',{
 hash:text('hash').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),expiresAt:integer('expires_at').notNull()
});
export const completions=sqliteTable('completions',{
 id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),chapter:integer('chapter').notNull(),createdAt:integer('created_at').notNull()
});

// Extended persistent systems. Atomic conditional batches in worker/game-data.mjs are part of the contract.
export const heroProgress=sqliteTable('hero_progress',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),unlockedChapter:integer('unlocked_chapter').notNull().default(1),skin:text('skin').notNull().default('default'),title:text('title').notNull().default(''),xp:integer('xp').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.hero]})]);
export const items=sqliteTable('items',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),catalogId:text('catalog_id').notNull(),quality:integer('quality').notNull().default(0),location:text('location').notNull().default('inventory'),bankClan:text('bank_clan'),bankTab:integer('bank_tab'),slot:text('slot').notNull(),equipped:integer('equipped').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('items_owner').on(t.accountId,t.hero),uniqueIndex('equipped_slot').on(t.accountId,t.hero,t.slot).where(sql`${t.equipped}=1`)]);
export const rewardEvents=sqliteTable('reward_events',{kind:text('kind').notNull().default(''),roundId:text('round_id').notNull().default(''),applied:integer('applied').notNull().default(0),id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),xp:integer('xp').notNull().default(0),gold:integer('gold').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('reward_lookup').on(t.accountId,t.hero,t.roundId,t.applied)]);
export const matches=sqliteTable('matches',{mythicLevel:integer('mythic_level').notNull().default(0),id:text('id').primaryKey(),mode:text('mode').notNull(),chapter:integer('chapter').notNull(),durationMs:integer('duration_ms').notNull(),outcome:text('outcome').notNull(),week:integer('week').notNull(),createdAt:integer('created_at').notNull()},t=>[index('match_rank').on(t.week,t.mode,t.chapter,t.outcome,t.durationMs)]);
export const matchPlayers=sqliteTable('match_players',{matchId:text('match_id').notNull().references(()=>matches.id),accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),name:text('name').notNull(),kills:integer('kills').notNull().default(0),outcome:text('outcome').notNull(),gold:integer('gold').notNull().default(0),itemId:text('item_id')},t=>[primaryKey({columns:[t.matchId,t.accountId]}),index('player_history').on(t.accountId,t.matchId)]);
export const friendships=sqliteTable('friendships',{a:text('a').notNull().references(()=>accounts.id),b:text('b').notNull().references(()=>accounts.id),requester:text('requester').notNull().references(()=>accounts.id),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.a,t.b]}),index('friends_b').on(t.b,t.status)]);
export const chatMessages=sqliteTable('chat_messages',{clanId:text('clan_id'),id:integer('id').primaryKey({autoIncrement:true}),sender:text('sender').notNull().references(()=>accounts.id),recipient:text('recipient').references(()=>accounts.id),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('chat_global').on(t.recipient,t.id),index('chat_private').on(t.sender,t.recipient,t.id)]);
export const presence=sqliteTable('presence',{accountId:text('account_id').notNull().references(()=>accounts.id),sessionHash:text('session_hash').notNull().references(()=>sessions.hash,{onDelete:'cascade'}),lastSeen:integer('last_seen').notNull()},t=>[primaryKey({columns:[t.accountId,t.sessionHash]}),index('presence_seen').on(t.lastSeen)]);
export const listings=sqliteTable('listings',{quantity:integer('quantity').notNull().default(1),id:text('id').primaryKey(),itemId:text('item_id').notNull().references(()=>items.id),seller:text('seller').notNull().references(()=>accounts.id),price:integer('price').notNull(),status:text('status').notNull().default('active'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('active_listing').on(t.itemId).where(sql`${t.status}='active'`),index('listings_active').on(t.status,t.createdAt)]);
export const sales=sqliteTable('sales',{quantity:integer('quantity').notNull().default(1),itemId:text('item_id').references(()=>items.id),seller:text('seller').references(()=>accounts.id),price:integer('price'),applied:integer('applied').notNull().default(0),id:text('id').primaryKey(),listingId:text('listing_id').notNull().unique().references(()=>listings.id),buyer:text('buyer').notNull().references(()=>accounts.id),hero:text('hero').notNull(),createdAt:integer('created_at').notNull()});

export const mythicKeys=sqliteTable('mythic_keys',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),chapter:integer('chapter').notNull(),week:integer('week').notNull(),level:integer('level').notNull().default(2),status:text('status').notNull().default('available'),runId:text('run_id'),resolved:integer('resolved').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.hero,t.chapter,t.week]}),uniqueIndex('key_run').on(t.runId)]);
export const clans=sqliteTable('clans',{id:text('id').primaryKey(),name:text('name').notNull(),nameKey:text('name_key').notNull().unique(),owner:text('owner').notNull().unique().references(()=>accounts.id),createdAt:integer('created_at').notNull(),paid:integer('paid').notNull().default(0)});
export const clanMembers=sqliteTable('clan_members',{accountId:text('account_id').primaryKey().references(()=>accounts.id),clanId:text('clan_id').notNull().references(()=>clans.id,{onDelete:'cascade'}),role:text('role').notNull().default('member'),joinedAt:integer('joined_at').notNull()},t=>[index('clan_roster').on(t.clanId)]);
export const clanRequests=sqliteTable('clan_requests',{clanId:text('clan_id').notNull().references(()=>clans.id,{onDelete:'cascade'}),accountId:text('account_id').notNull().references(()=>accounts.id),kind:text('kind').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.clanId,t.accountId,t.kind]})]);
export const paymentOrders=sqliteTable('payment_orders',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),providerId:text('provider_id').unique(),amountCents:integer('amount_cents').notNull(),coins:integer('coins').notNull(),status:text('status').notNull().default('creating'),granted:integer('granted').notNull().default(0),live:integer('live').notNull().default(1),updatedAt:integer('updated_at').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('payment_owner').on(t.accountId,t.createdAt)]);

export const professions=sqliteTable('professions',{accountId:text('account_id').notNull().references(()=>accounts.id),profession:text('profession').notNull(),paid:integer('paid').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.profession]})]);
export const recipes=sqliteTable('recipes',{accountId:text('account_id').notNull().references(()=>accounts.id),recipe:text('recipe').notNull()},t=>[primaryKey({columns:[t.accountId,t.recipe]})]);
export const operations=sqliteTable('economy_operations',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),kind:text('kind').notNull(),applied:integer('applied').notNull().default(0),createdAt:integer('created_at').notNull()});
export const hotbar=sqliteTable('hero_hotbar',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),slot:integer('slot').notNull(),catalogId:text('catalog_id').notNull()},t=>[primaryKey({columns:[t.accountId,t.hero,t.slot]})]);
export const potionCooldowns=sqliteTable('potion_cooldowns',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),until:integer('until').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.hero]})]);
export const mail=sqliteTable('mail',{id:text('id').primaryKey(),accountId:text('account_id').notNull().references(()=>accounts.id),subject:text('subject').notNull(),body:text('body').notNull(),gold:integer('gold').notNull().default(0),isRead:integer('is_read').notNull().default(0),claimed:integer('claimed').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[index('mail_owner').on(t.accountId,t.createdAt)]);
export const weeklyClaims=sqliteTable('weekly_claims',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull(),week:integer('week').notNull(),level:integer('level').notNull(),itemId:text('item_id').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.accountId,t.hero,t.week]})]);
export const achievements=sqliteTable('achievements',{accountId:text('account_id').notNull().references(()=>accounts.id),hero:text('hero').notNull().default('account'),achievement:text('achievement').notNull(),seen:integer('seen').notNull().default(0),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.accountId,t.hero,t.achievement]})]);
export const skins=sqliteTable('skins',{accountId:text('account_id').notNull().references(()=>accounts.id),skin:text('skin').notNull(),paid:integer('paid').notNull().default(0)},t=>[primaryKey({columns:[t.accountId,t.skin]})]);
export const bankTabs=sqliteTable('clan_bank_tabs',{clanId:text('clan_id').notNull().references(()=>clans.id,{onDelete:'cascade'}),tab:integer('tab').notNull(),name:text('name').notNull(),paid:integer('paid').notNull().default(0)},t=>[primaryKey({columns:[t.clanId,t.tab]})]);

export const listingItems=sqliteTable('listing_items',{listingId:text('listing_id').notNull().references(()=>listings.id),itemId:text('item_id').notNull().references(()=>items.id)},t=>[primaryKey({columns:[t.listingId,t.itemId]}),index('listing_items_item').on(t.itemId)]);
