import {HEROES,CHAPTERS} from './engine.js';
const $=(id:string)=>document.getElementById(id)!;
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const attrs:Record<string,string>={maxHp:'Vida',damage:'Dano',defense:'Defesa',speed:'Movimento',attackSpeed:'Vel. ataque'};
const bonuses=(d:any)=>Object.entries(d?.attributes??{}).map(([k,v])=>`+${v} ${attrs[k]??k}`).join(' · ');
export class Adventure {
 crafting=false;profession='alchemy';recipe='healing_potion';craftHero='';bankTab=1;bank:any;mailPage=1;epoch=0;noticed=new Set<string>();
 constructor(public hub:any){
  $('find-rooms').onclick=()=>{this.hub.setTab('rooms');};$('rooms-chapter').onchange=()=>void this.rooms();$('rooms-refresh').onclick=()=>void this.rooms();
  window.addEventListener('keydown',e=>{if(e.key==='Shift')document.body.classList.add('inspect-items');});window.addEventListener('keyup',e=>{if(e.key==='Shift')document.body.classList.remove('inspect-items');});window.addEventListener('blur',()=>document.body.classList.remove('inspect-items'));
  const status=$('hub-status');let timer:any;new MutationObserver(()=>{clearTimeout(timer);if(status.textContent)timer=setTimeout(()=>status.textContent='',6500);}).observe(status,{childList:true});
 }
 request(path:string,data?:any){return this.hub.features.request(path,data);}
 action(fn:()=>Promise<any>,button?:HTMLButtonElement){return this.hub.features.action(fn,button);}
 get profile(){return this.hub.profile;}
 get hero(){return this.hub.scene.selectedHero;}
 get owned(){return this.profile?.heroes.find((h:any)=>h.id===this.hero);}
 heroOptions(selected=this.hero){return Object.entries(HEROES).map(([id,h])=>`<option value="${id}" ${id===selected?'selected':''}>${h.name}</option>`).join('');}
 accepted(){
  for(const a of this.profile?.achievements??[]){const key=`${this.profile.id}:${a.hero}:${a.achievement}`;if(!a.seen&&!this.noticed.has(key)){this.noticed.add(key);const def=this.profile.catalog.achievements[a.achievement];this.hub.features.notice(`Conquista desbloqueada: ${def.name}${a.hero==='account'?'':` · ${HEROES[a.hero].name}`}!`);void this.request('achievements/seen',{}).catch(()=>{});}}
  $('tab-mail').textContent=`Email${this.profile?.unreadMail?` (${this.profile.unreadMail})`:''}`;this.heroExtras();
 }
 open(tab:string){this.epoch++;if(tab==='shop')this.shop();if(tab==='professions')this.professions();if(tab==='achievements')this.achievements();if(tab==='mail')void this.mail();if(tab==='rooms')void this.rooms();}
 async mutate(path:string,data:any,b?:HTMLButtonElement){await this.action(async()=>{await this.request(path,data);await this.hub.refresh(false);this.open(this.hub.tab);},b);}
 dialog(title:string,body:string,confirm:string,fn:()=>Promise<any>){const dialog=$('trade-dialog') as HTMLDialogElement;$('trade-content').innerHTML=`<span class="eyebrow">EMBERFALL</span><h2>${esc(title)}</h2>${body}<p id="trade-error" role="status"></p><div class="item-actions"><button type="button" id="trade-cancel" class="outline-button">Cancelar</button><button id="trade-confirm" class="primary-button">${esc(confirm)}</button></div>`;$('trade-cancel').onclick=()=>dialog.close();($('trade-content') as HTMLFormElement).onsubmit=async e=>{e.preventDefault();const b=$('trade-confirm') as HTMLButtonElement;b.disabled=true;try{await fn();dialog.close();await this.hub.refresh(false);this.open(this.hub.tab);if(this.hub.tab==='clan')await this.renderBank();}catch(e:any){$('trade-error').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 heroExtras(){if(!this.owned)return;const h=this.owned,keys=(this.profile.weeklyKeys??[]).filter((k:any)=>k.hero===this.hero),level=Math.max(0,...keys.map((k:any)=>k.level)),claimed=this.profile.weeklyClaims?.some((c:any)=>c.hero===this.hero);const title=h.title==='dragon_hunter'?(['lyra','sylva'].includes(this.hero)?'Caçadora de dragões':'Caçador de dragões'):'';
  $('roster-name').textContent=HEROES[this.hero].name+(title?', '+title.toLowerCase():'');
  $('hero-extras').innerHTML=`<button id="weekly-claim" class="outline-button" ${!level||claimed?'disabled':''}>${claimed?'BAÚ SEMANAL RESGATADO':level?`RESGATAR BAÚ · MÍTICA +${level}`:'BAÚ · SEM RECOMPENSA ANTERIOR'}</button><small>${claimed?'Novo resgate na próxima semana.':'Um equipamento por herói. A melhor chave válida da semana anterior define a recompensa; a semana atual prepara o próximo baú.'}</small><label>Título<select id="hero-title"><option value="">Nenhum</option>${(this.profile.achievements??[]).filter((a:any)=>a.hero===this.hero&&this.profile.catalog.achievements[a.achievement]?.title).map((a:any)=>`<option value="${a.achievement}" ${a.achievement===h.title?'selected':''}>${['lyra','sylva'].includes(this.hero)?'Caçadora':'Caçador'} de dragões</option>`).join('')}</select></label>${this.hero==='kael'?`<label>Aparência<select id="hero-skin"><option value="default">Kael · Padrão</option>${(this.profile.skins??[]).filter((s:string)=>s==='kael_astral').map((s:string)=>`<option value="${s}" ${h.skin===s?'selected':''}>Guardião Astral</option>`).join('')}</select></label>`:''}`;
  $('weekly-claim').onclick=()=>this.dialog('Resgatar o baú semanal?',`<p>Herói: ${HEROES[this.hero].name} · melhor chave da semana anterior +${level}. As chaves desta semana não alteram este resgate.</p>`,'RESGATAR',async()=>{const d=await this.request('weekly/claim',{hero:this.hero});this.hub.features.notice(`Baú resgatado: ${d.item.name}.`);});
  $('hero-title').onchange=()=>void this.mutate('title',{hero:this.hero,title:($('hero-title') as HTMLSelectElement).value});if($('hero-skin'))$('hero-skin').onchange=()=>void this.mutate('skins/equip',{hero:this.hero,skin:($('hero-skin') as HTMLSelectElement).value});
  const hotbar=(this.profile.hotbar??[]).filter((b:any)=>b.hero===this.hero),potions=h.inventory.filter((i:any)=>i.definition.kind==='consumable'&&!i.listed);const types=[...new Set<string>(potions.map((i:any)=>i.catalog_id))];
  $('hero-hotbar').innerHTML=Array.from({length:5},(_,i)=>{const slot=i+1,current=hotbar.find((b:any)=>b.slot===slot)?.catalog_id;return `<label class="hotbar-slot"><kbd>${slot}</kbd><select data-hotbar="${slot}" aria-label="Consumível no atalho ${slot}"><option value="">Vazio</option>${[...new Set([...types,...(current?[current]:[])])].map(c=>`<option value="${c}" ${c===current?'selected':''}>${esc(this.profile.catalog.items[c].name)} ×${potions.filter((p:any)=>p.catalog_id===c).length}</option>`).join('')}</select></label>`;}).join('');
  $('hero-hotbar').querySelectorAll<HTMLSelectElement>('[data-hotbar]').forEach(b=>b.onchange=()=>void this.mutate('hotbar',{hero:this.hero,slot:Number(b.dataset.hotbar),catalog:b.value}));
 }
 professions(){const p=this.profile;if(!p)return;const professions=p.catalog.professions;this.craftHero||=this.hero;const h=p.heroes.find((h:any)=>h.id===this.craftHero),unlocked=p.professions.includes(this.profession),recipes=Object.values(p.catalog.recipes).filter((r:any)=>r.profession===this.profession&&p.recipes.includes(r.id)) as any[];if(!recipes.some(r=>r.id===this.recipe))this.recipe=recipes[0]?.id??'';const r=recipes.find(r=>r.id===this.recipe);
  $('professions-content').innerHTML=`<nav class="profession-list" aria-label="Profissões">${Object.entries(professions).map(([id,name])=>`<button class="${id===this.profession?'active':''}" data-profession="${id}"><span>${esc(name)}</span><small>${p.professions.includes(id)?'Aprendida':'100 gold'}</small></button>`).join('')}</nav><section class="recipe-list"><span class="eyebrow">SEU OFÍCIO</span><h2>${esc(professions[this.profession])}</h2>${!unlocked?'<p>Aprenda esta profissão para descobrir novas receitas.</p><button id="profession-unlock" class="primary-button">APRENDER · 100 GOLD</button>':recipes.length?recipes.map(r=>`<button data-recipe="${r.id}" class="recipe-option ${r.id===this.recipe?'active':''}">⚗ ${esc(r.name)}</button>`).join(''):'<p class="empty-state">Nenhuma receita aprendida. Encontre receitas nos capítulos ou compre no mercado e aprenda pelo inventário.</p>'}</section><section class="craft-detail">${r?`<span class="item-emblem">⚗</span><span class="eyebrow">ALQUIMIA</span><h2>${esc(r.name)}</h2><p>${esc(p.catalog.items[r.output].description)}</p><label>Produzir para<select id="craft-hero">${this.heroOptions(this.craftHero)}</select></label><h3>Materiais necessários</h3>${Object.entries(r.materials).map(([id,count])=>{const n=h.inventory.filter((i:any)=>i.catalog_id===id&&!i.listed&&!i.equipped).length;return `<div class="material-row"><span>${esc(p.catalog.items[id].name)}</span><b class="${n<Number(count)?'insufficient':''}">${n} / ${count}</b></div>`;}).join('')}<button id="craft-item" class="primary-button" ${Object.entries(r.materials).some(([id,c])=>h.inventory.filter((i:any)=>i.catalog_id===id&&!i.listed&&!i.equipped).length<Number(c))?'disabled':''}>CRIAR POÇÃO</button><small>Materiais e resultado ficam no inventário do herói escolhido.</small>`:'<div class="empty-state"><span class="item-emblem">✧</span><h2>Um novo conhecimento</h2><p>Selecione uma receita aprendida para ver seus materiais e resultado.</p></div>'}</section>`;
  $('professions-content').querySelectorAll<HTMLButtonElement>('[data-profession]').forEach(b=>b.onclick=()=>{this.profession=b.dataset.profession!;this.professions();});$('professions-content').querySelectorAll<HTMLButtonElement>('[data-recipe]').forEach(b=>b.onclick=()=>{this.recipe=b.dataset.recipe!;this.professions();});if($('profession-unlock'))$('profession-unlock').onclick=()=>this.dialog('Aprender profissão?',`<p>${esc(professions[this.profession])} custa 100 gold da conta. As receitas são aprendidas separadamente.</p>`,'APRENDER',()=>this.request('professions/unlock',{profession:this.profession}));if(r){$('craft-hero').onchange=()=>{this.craftHero=($('craft-hero') as HTMLSelectElement).value;this.professions();};$('craft-item').onclick=()=>void this.craft(r.id);if(this.crafting){($('craft-item') as HTMLButtonElement).disabled=true;$('craft-item').textContent='FABRICANDO…';}}
 }
 async craft(recipe:string){
  if(this.crafting)return;this.crafting=true;const account=this.profile.id,hero=this.craftHero,button=$('craft-item') as HTMLButtonElement;button.disabled=true;button.classList.add('crafting');button.setAttribute('aria-busy','true');button.innerHTML='<span class="craft-fill" aria-hidden="true"></span><span class="craft-label">FABRICANDO…</span>';this.hub.scene.craftSound(false);
  try{const results=await Promise.allSettled([this.request('craft',{hero,recipe}),new Promise(resolve=>setTimeout(resolve,1500))]);if(results[0].status==='rejected')throw results[0].reason;if(this.profile?.id!==account)return;this.hub.scene.craftSound(true);await this.hub.refresh(false);this.hub.features.notice('Fabricação concluída. Poção entregue ao inventário de '+HEROES[hero].name+'.');}catch(e:any){if(this.profile?.id===account)this.hub.features.notice(e.message);}finally{this.crafting=false;if(this.profile?.id===account&&this.hub.tab==='professions')this.professions();}
 }
 achievements(){const p=this.profile;$('achievements-content').innerHTML=['account','hero'].map(scope=>`<section><h2>${scope==='account'?'Conquistas da conta':`Conquistas de ${HEROES[this.hero].name}`}</h2>${Object.values(p.catalog.achievements).filter((d:any)=>d.scope===scope).map((d:any)=>{const a=p.achievements.find((a:any)=>a.achievement===d.id&&a.hero===(scope==='account'?'account':this.hero));return `<article class="achievement-card ${a?'unlocked':''}"><span class="item-emblem">${a?'✦':'◇'}</span><div><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p><small>${a?`Obtida em ${new Date(a.created_at).toLocaleDateString('pt-BR')}`:'Ainda não obtida'}${d.title?' · libera título para este herói':''}</small></div></article>`;}).join('')}</section>`).join('');$('achievement-hero').innerHTML=this.heroOptions();$('achievement-hero').onchange=()=>{this.hub.scene.selectHero(($('achievement-hero') as HTMLSelectElement).value);this.achievements();};}
 async mail(){const epoch=this.epoch;await this.action(async()=>{const d=await this.request('mail?page='+this.mailPage);if(epoch!==this.epoch||this.hub.tab!=='mail')return;$('mail-content').innerHTML=`<div class="section-toolbar"><p>Vendas concluídas chegam aqui. Colete os anexos para receber seu gold.</p><button id="mail-all" class="outline-button">Ler e coletar todos</button></div>${d.messages.length?d.messages.map((m:any)=>`<article class="mail-card ${m.is_read?'read':'unread'}"><div><small>${new Date(m.created_at).toLocaleString('pt-BR')}</small><h3>${esc(m.subject)}</h3>${m.is_read?`<p>${esc(m.body)}</p>`:''}<span>${m.gold?`✦ ${m.gold} gold ${m.claimed?'· coletado':''}`:''}</span></div><div class="item-actions">${!m.is_read?`<button class="mini-button" data-read="${esc(m.id)}">Ler</button>`:''}<button class="mini-primary" data-claim="${esc(m.id)}" ${m.claimed?'disabled':''}>${m.claimed?'Coletado':m.gold?'Ler e coletar':'Marcar como lido'}</button></div></article>`).join(''):'<p class="empty-state">Sua caixa de entrada está vazia.</p>'}`;
  $('mail-all').onclick=()=>void this.mutate('mail/claim',{all:true});for(const op of ['read','claim'])$('mail-content').querySelectorAll<HTMLButtonElement>(`[data-${op}]`).forEach(b=>b.onclick=()=>void this.mutate('mail/'+op,{mail:b.dataset[op]},b));this.hub.features.pager('mail-pages',d.page,d.hasMore,(p:number)=>{this.mailPage=p;void this.mail();});});}
 shop(){const p=this.profile,owned=p.skins.includes('kael_astral');$('shop-content').innerHTML=`<div class="section-toolbar"><p>Uma nova aparência para sua jornada.</p><button id="shop-recharge" class="outline-button">◈ ${p.gems} gemas · Recarregar</button></div><div class="store-grid"><article class="skin-product"><div class="skin-preview"><img id="shop-skin-image" alt="Kael Guardião Astral"/><span>APARÊNCIA EXCLUSIVA</span></div><div class="skin-description"><span class="eyebrow">KAEL</span><h2>Guardião Astral</h2><p>A mesma espada. Um novo juramento sob as estrelas.</p><small>Skin cosmética · disponível para Kael</small><div class="item-actions"><strong>◈ 10 gemas</strong><button id="skin-buy" class="primary-button" ${owned?'disabled':''}>${owned?'ADQUIRIDA':'COMPRAR SKIN'}</button></div></div></article></div>`;($('shop-skin-image') as HTMLImageElement).src=this.hub.scene.textures.get('kael_astral-idle').getSourceImage().toDataURL();$('shop-recharge').onclick=()=>void this.hub.expansion.recharge();$('skin-buy').onclick=()=>this.dialog('Adquirir Guardião Astral?',`<p>A compra usa 10 gemas da conta. Depois, escolha a aparência na página de heróis.</p>`,'COMPRAR · 10 GEMAS',async()=>{await this.request('skins/buy',{skin:'kael_astral'});});}
 async renderBank(){if(!$('clan-bank'))return;const account=this.profile.id;await this.action(async()=>{const d=await this.request('bank');if(!$('clan-bank')||account!==this.profile?.id)return;this.bank=d;if(!d.tabs.some((t:any)=>t.tab===this.bankTab))this.bankTab=1;const current=d.tabs.find((t:any)=>t.tab===this.bankTab),next=d.tabs.length+1,items=d.items.filter((i:any)=>i.bank_tab===this.bankTab);$('clan-bank').innerHTML=`<span class="eyebrow">TESOUROS COMPARTILHADOS</span><h2>Baú do clã</h2><div class="bank-tabs">${d.tabs.map((t:any)=>`<button data-bank-tab="${t.tab}" class="${t.tab===this.bankTab?'active':''}">${esc(t.name)}</button>`).join('')}${next<=8?`<button id="bank-unlock" ${d.owner?'':'disabled'}>🔒 Aba ${next} · ${(next-4)*500} gold</button>`:''}</div><div class="section-toolbar"><p>Todos os membros podem depositar e retirar itens.</p><div>${d.owner?'<button id="bank-rename" class="mini-button">Renomear aba</button>':''}<button id="bank-deposit" class="outline-button">Depositar item</button></div></div><div class="item-grid">${items.map((i:any)=>`<article class="item-card"><strong>${esc(i.definition.name)}</strong><p>${bonuses(i.definition)||esc(i.definition.description??'')}</p><button data-withdraw="${esc(i.id)}" class="mini-primary">Retirar para um herói</button></article>`).join('')||'<p class="empty-state">Esta aba está vazia.</p>'}</div>`;
  $('clan-bank').querySelectorAll<HTMLButtonElement>('[data-bank-tab]').forEach(b=>b.onclick=()=>{this.bankTab=Number(b.dataset.bankTab);void this.renderBank();});if($('bank-unlock'))$('bank-unlock').onclick=()=>this.dialog('Liberar próxima aba?',`<p>Aba ${next}: ${(next-4)*500} gold da sua conta.</p>`,'LIBERAR',()=>this.request('bank/unlock',{tab:next}));if($('bank-rename'))$('bank-rename').onclick=()=>this.dialog('Nome da aba',`<label>Nome<input id="bank-name" maxlength="24" required value="${esc(current.name)}"/></label>`,'SALVAR',()=>this.request('bank/rename',{tab:this.bankTab,name:($('bank-name') as HTMLInputElement).value}));
  $('bank-deposit').onclick=()=>{const items=this.profile.heroes.flatMap((h:any)=>h.inventory.filter((i:any)=>!i.equipped&&!i.listed&&!i.hotbar).map((i:any)=>({...i,hero:h.id})));this.dialog('Depositar no baú',`<label>Item do inventário<select id="bank-item" required>${items.map((i:any)=>`<option value="${esc(i.id)}">${HEROES[i.hero].name} · ${esc(i.definition.name)}</option>`).join('')}</select></label><label>Aba de destino<select id="bank-destination">${d.tabs.map((t:any)=>`<option value="${t.tab}" ${t.tab===this.bankTab?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><p>O item passará a pertencer ao baú compartilhado.</p>`,'DEPOSITAR',()=>this.request('bank/deposit',{item:($('bank-item') as HTMLSelectElement).value,tab:Number(($('bank-destination') as HTMLSelectElement).value)}));};
  $('clan-bank').querySelectorAll<HTMLButtonElement>('[data-withdraw]').forEach(b=>b.onclick=()=>this.dialog('Retirar item do baú',`<label>Entregar para<select id="bank-hero">${this.heroOptions()}</select></label>`,'RETIRAR',()=>this.request('bank/withdraw',{item:b.dataset.withdraw,hero:($('bank-hero') as HTMLSelectElement).value})));});}
 async rooms(){const epoch=this.epoch;await this.action(async()=>{const d=await this.request(`rooms?hero=${this.hero}&chapter=${($('rooms-chapter') as HTMLSelectElement).value}`);if(epoch!==this.epoch||this.hub.tab!=='rooms')return;$('rooms-content').innerHTML=d.rooms.length?d.rooms.map((r:any)=>`<article class="room-card"><div><span class="eyebrow">PVE · ${r.players}/${r.maxPlayers} JOGADORES</span><h2>${CHAPTERS[r.chapter].name}${r.mythicLevel?` · Mítica +${r.mythicLevel}`:''}</h2><p>Líder: ${esc(r.host)} · Sala ${esc(r.code)}</p></div><button class="primary-button" data-room="${esc(r.code)}">ENTRAR</button></article>`).join(''):'<p class="empty-state">Nenhuma sala pública disponível para o progresso deste herói. Crie uma sala PvE no mapa e marque “Visível na busca”.</p>';$('rooms-content').querySelectorAll<HTMLButtonElement>('[data-room]').forEach(b=>b.onclick=()=>{this.hub.scene.selectedMode='coop';$('multiplayer').click();($('mp-code') as HTMLInputElement).value=b.dataset.room!;$('mp-join').click();});});}
}
