const $=(id:string)=>document.getElementById(id)!;
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:number)=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),date=(n:any)=>new Date(n).toLocaleString('pt-BR');
const states:Record<string,string>={creating:'Aguardando geração',pending:'Aguardando Pix',in_process:'Em análise',approved:'Pago',rejected:'Recusado',cancelled:'Cancelado',refunded:'Estornado',charged_back:'Estornado',in_mediation:'Em análise',authorized:'Em análise'};
export class Expansion {
 transactionPage=1;orderId='';epoch=0;account='';clan:any=null;polling=false;
 constructor(private hub:any){$('transaction-side').onchange=()=>{this.transactionPage=1;void this.transactions();};setInterval(()=>{if(!this.hub.profile||document.hidden||this.hub.scene.session!=='menu'||this.polling)return;this.polling=true;const task=this.hub.tab==='shop'&&this.orderId?this.refreshOrder():this.hub.tab==='clan'&&this.clan?this.clanChat():Promise.resolve();void task.finally(()=>this.polling=false);},8000);}
 request(path:string,value?:any){return this.hub.features.request(path,value);}
 action(fn:()=>Promise<any>,b?:HTMLButtonElement){return this.hub.features.action(fn,b);}
 reset(){this.epoch++;this.orderId='';this.clan=null;for(const id of ['shop-content','clan-content','transaction-content'])$(id).replaceChildren();}
 accepted(){if(this.account!==this.hub.profile.id){this.reset();this.account=this.hub.profile.id;}}
 open(tab:string){if(tab==='shop')void this.shop();if(tab==='clan')void this.loadClan();if(tab==='market')void this.transactions();}
 async transactions(){const epoch=this.epoch,id=this.hub.profile?.id;await this.action(async()=>{const d=await this.request(`market/history?page=${this.transactionPage}&side=${($('transaction-side') as HTMLSelectElement).value}`);if(epoch!==this.epoch||id!==this.hub.profile?.id)return;$('transaction-content').innerHTML=d.transactions.length?`<table><thead><tr><th>Data</th><th>Operação</th><th>Item</th><th>Jogador</th><th>Gold</th></tr></thead><tbody>${d.transactions.map((t:any)=>`<tr><td>${date(t.created_at)}</td><td>${t.buyer===id?'Compra':'Venda'}</td><td>${esc(t.definition?.name)}</td><td>${esc(t.buyer===id?t.seller_name:t.buyer_name)}</td><td>${t.buyer===id?'−':'+'}${t.price}</td></tr>`).join('')}</tbody></table>`:'<p class="empty-state">Suas compras e vendas concluídas aparecem aqui.</p>';this.hub.features.pager('transaction-pages',d.page,d.hasMore,(p:number)=>{this.transactionPage=p;void this.transactions();});});}
 shop(){this.hub.adventure.shop();}
 async recharge(){const epoch=this.epoch;await this.action(async()=>{const d=await this.request('shop');if(epoch!==this.epoch||this.hub.tab!=='shop')return;
  $('shop-content').innerHTML=`<button id="shop-back" class="text-button">← Voltar à loja</button><div class="shop-layout"><article class="premium-pack"><span class="premium-symbol">◈</span><span class="eyebrow">CRISTAIS · MOEDA PREMIUM</span><h2>${d.product.coins} cristais</h2><p>Saldo da conta. Gold continua sendo obtido nas jornadas.</p><strong class="pack-price">${money(d.product.amountCents)}</strong><small>Pagamento via Pix · entrega após confirmação</small></article><div class="checkout-panel"><h2>${d.configured?'Pagar com Pix':'Em preparação'}</h2><p>${d.configured?(d.live?'Confira o valor antes de pagar no aplicativo do seu banco.':'Ambiente de teste: pagamentos simulados não entregam moedas reais.'):'O vendedor precisa configurar a integração para liberar as compras.'}</p>${d.configured?'<form id="pix-form"><label>E-mail do pagador<input id="pix-email" type="email" autocomplete="email" maxlength="254" required/></label><label>CPF do pagador<input id="pix-cpf" inputmode="numeric" autocomplete="off" pattern="[0-9]{11}" maxlength="11" placeholder="11 dígitos, sem pontuação" required/></label><button id="pix-generate" class="primary-button">GERAR PIX</button><small>Se a geração falhar, tente novamente com os mesmos dados. O preço permanece R$ 0,01.</small></form>':''}<p id="pix-status" role="status"></p><div id="pix-payment"></div></div></div><h2>Suas cobranças recentes</h2><div class="data-table"><table><thead><tr><th>Data</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${d.orders.map((o:any)=>`<tr><td>${date(o.created_at)}</td><td>${money(o.amount_cents)}</td><td>${esc(states[o.status]??o.status)}${o.live?'':' · teste'}</td><td><button class="mini-button" data-order="${esc(o.id)}">Consultar</button></td></tr>`).join('')}</tbody></table></div>`;
  $('shop-back').onclick=()=>this.shop();
  if(d.configured)$('pix-form').onsubmit=async e=>{e.preventDefault();const b=$('pix-generate') as HTMLButtonElement;b.disabled=true;this.orderId||=crypto.randomUUID();$('pix-status').textContent='Gerando cobrança…';try{const p=await this.request('shop/checkout',{order:this.orderId,email:($('pix-email') as HTMLInputElement).value.trim(),cpf:($('pix-cpf') as HTMLInputElement).value});if(epoch===this.epoch&&this.hub.tab==='shop'){this.showOrder(p);($('pix-cpf') as HTMLInputElement).value='';}}catch(e:any){if($('pix-status'))$('pix-status').textContent=e.message;}finally{b.disabled=false;}};
  $('shop-content').querySelectorAll<HTMLButtonElement>('[data-order]').forEach(b=>b.onclick=()=>{this.orderId=b.dataset.order!;void this.refreshOrder();});if(this.orderId)await this.refreshOrder();
 });}
 showOrder(o:any){if(!$('pix-payment'))return;const pending=['pending','in_process','creating'].includes(o.status);$('pix-status').textContent=o.status==='approved'?(o.live?`Pagamento confirmado. ${o.granted} cristais entregues à conta.`:'Teste confirmado. Nenhuma moeda real foi entregue.'):states[o.status]??o.status;
  $('pix-payment').innerHTML=`${pending&&o.qr?`${o.qrImage?`<img class="pix-qr" alt="QR Code Pix" src="data:image/png;base64,${esc(o.qrImage)}"/>`:''}<label>Pix copia e cola<textarea readonly>${esc(o.qr)}</textarea></label><button id="pix-copy" class="outline-button">Copiar código Pix</button>${o.expiresAt?`<p>Validade: ${date(o.expiresAt)}</p>`:''}`:''}<button id="pix-refresh" class="text-button">Atualizar pagamento</button><button id="pix-new" class="text-button">Preparar nova compra</button>`;
  if($('pix-copy'))$('pix-copy').onclick=()=>void navigator.clipboard.writeText(o.qr).then(()=>$('pix-status').textContent='Código Pix copiado.').catch(()=>$('pix-status').textContent='Selecione e copie o código acima.');$('pix-refresh').onclick=()=>void this.refreshOrder();$('pix-new').onclick=()=>{this.orderId='';void this.recharge();};
 }
 async refreshOrder(){const id=this.orderId,epoch=this.epoch;if(!id)return;try{const o=await this.request('shop/order/'+encodeURIComponent(id));if(epoch!==this.epoch||id!==this.orderId||this.hub.tab!=='shop')return;this.showOrder(o);if(['approved','refunded','charged_back'].includes(o.status))await this.hub.refresh(false);}catch(e:any){if(epoch===this.epoch&&$('pix-status'))$('pix-status').textContent=e.message;}}
 async loadClan(){const epoch=this.epoch;await this.action(async()=>{const d=await this.request('clan?page=1');if(epoch!==this.epoch||this.hub.tab!=='clan')return;this.clan=d.clan;const c=d.clan;
  if(!c){$('clan-content').innerHTML=`<div class="clan-grid"><section class="clan-card"><h2>Erga seu estandarte</h2><p>Criação: <strong>✦ 1.000 gold</strong> da conta.</p><form id="clan-create"><label>Nome do clã<input id="clan-name" minlength="3" maxlength="32" required/></label><button class="primary-button">CRIAR CLÃ · 1.000 GOLD</button></form></section><section class="clan-card"><h2>Convites recebidos</h2>${d.invites.map((c:any)=>`<div class="friend-row"><strong>${esc(c.name)}</strong><button class="mini-primary" data-clan-join="${esc(c.id)}">Aceitar convite</button></div>`).join('')||'<p>Nenhum convite recebido.</p>'}</section></div><h2>Encontre sua companhia</h2><form id="clan-search" class="feature-filters"><input id="clan-query" maxlength="32" placeholder="Pesquisar clã"/><button class="outline-button">Buscar</button></form><div id="clan-directory"></div><div id="clan-pages" class="pagination"></div>`;
   $('clan-create').onsubmit=e=>{e.preventDefault();const name=($('clan-name') as HTMLInputElement).value.trim();this.confirm('Criar clã por 1.000 gold?','Excluir o clã não devolve o custo.',()=>this.request('clan/create',{name}));};$('clan-content').querySelectorAll<HTMLButtonElement>('[data-clan-join]').forEach(b=>b.onclick=()=>void this.mutate('accept-invite',{clan:b.dataset.clanJoin},b));$('clan-search').onsubmit=e=>{e.preventDefault();void this.directory(1);};this.showDirectory(d);return;
  }
  const admin=c.role==='admin',owner=c.owner===this.hub.profile.id;
  $('clan-content').innerHTML=`<div class="clan-heading"><div><span class="eyebrow">SEU ESTANDARTE</span><h2>${esc(c.name)}</h2><p>${d.members.length} membros · ${owner?'Fundador':admin?'Administrador':'Membro'}</p></div><button id="clan-refresh" class="outline-button">Atualizar membros</button></div><div class="clan-grid"><section class="clan-card"><h2>Membros</h2><div class="clan-members">${d.members.map((m:any)=>`<div class="friend-row"><span class="presence ${m.online?'online':'offline'}"></span><div><strong>${esc(m.name)}</strong><small>${m.online?'Online':'Offline'} · ${m.id===c.owner?'Fundador':m.role==='admin'?'Admin':'Membro'}</small></div><div class="request-actions">${owner&&m.id!==c.owner?`<button class="mini-button" data-role="${m.role==='admin'?'member':'admin'}" data-member="${esc(m.id)}">${m.role==='admin'?'Rebaixar':'Tornar admin'}</button>`:''}${admin&&m.id!==c.owner&&(owner||m.role==='member')?`<button class="mini-button" data-kick="${esc(m.id)}">Remover</button>`:''}</div></div>`).join('')}</div>${admin?'<form id="clan-invite" class="feature-filters"><label>Convidar jogador<input id="clan-invite-name" minlength="3" maxlength="18" placeholder="Nome de usuário" required/></label><button class="outline-button">Convidar</button></form>':''}</section><section class="clan-card"><h2>Chat do clã</h2><div id="clan-messages" class="chat-messages"></div><form id="clan-chat-form" class="chat-form"><input id="clan-message" maxlength="500" placeholder="Converse com seu clã…" required/><button title="Enviar">↑</button></form></section></div>${admin?`<section class="clan-card"><h2>Aplicações pendentes</h2>${d.applications.map((m:any)=>`<div class="friend-row"><strong>${esc(m.name)}</strong><button class="mini-primary" data-approve="${esc(m.id)}">Aprovar</button><button class="mini-button" data-reject="${esc(m.id)}">Recusar</button></div>`).join('')||'<p>Nenhuma aplicação pendente.</p>'}</section>`:''}<section id="clan-bank" class="clan-card"></section><button id="clan-exit" class="outline-button">${owner?'Excluir clã':'Sair do clã'}</button>`;
  $('clan-refresh').onclick=()=>void this.loadClan();for(const op of ['approve','reject'])$('clan-content').querySelectorAll<HTMLButtonElement>(`[data-${op}]`).forEach(b=>b.onclick=()=>void this.mutate(op,{target:b.dataset[op]},b));$('clan-content').querySelectorAll<HTMLButtonElement>('[data-role]').forEach(b=>b.onclick=()=>void this.mutate('role',{target:b.dataset.member,role:b.dataset.role},b));$('clan-content').querySelectorAll<HTMLButtonElement>('[data-kick]').forEach(b=>b.onclick=()=>this.confirm('Remover membro?','Ele perderá o acesso ao chat do clã.',()=>this.request('clan/kick',{target:b.dataset.kick})));
  $('clan-content').querySelectorAll<HTMLButtonElement>('[data-chest]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-chest]').forEach(el=>el.classList.toggle('active',el===b));$('chest-label').textContent=`Aba ${b.dataset.chest} · armazenamento ainda indisponível.`;});if(admin)$('clan-invite').onsubmit=e=>{e.preventDefault();void this.mutate('invite',{username:($('clan-invite-name') as HTMLInputElement).value});};$('clan-exit').onclick=()=>this.confirm(owner?'Excluir este clã?':'Sair deste clã?',owner?'Membros, solicitações e mensagens serão removidos. Esta ação é definitiva.':'Você precisará de um novo convite para voltar.',()=>this.request(owner?'clan/delete':'clan/leave',{}));
  $('clan-chat-form').onsubmit=async e=>{e.preventDefault();const input=$('clan-message') as HTMLInputElement,body=input.value;await this.action(async()=>{await this.request('chat/send',{channel:'clan',body});if(input.value===body)input.value='';await this.clanChat();});};await this.clanChat();await this.hub.adventure.renderBank();
 });}
 async directory(page:number){const epoch=this.epoch;await this.action(async()=>{const d=await this.request(`clan?page=${page}&q=${encodeURIComponent(($('clan-query') as HTMLInputElement).value)}`);if(epoch===this.epoch&&this.hub.tab==='clan'&&!this.clan)this.showDirectory(d);});}
 showDirectory(d:any){$('clan-directory').innerHTML=d.clans.slice(0,20).map((c:any)=>`<div class="friend-row"><div><strong>${esc(c.name)}</strong><small>${c.members} membros</small></div><button class="mini-primary" data-clan-apply="${esc(c.id)}" ${c.applied?'disabled':''}>${c.applied?'Aplicação enviada':'Aplicar'}</button></div>`).join('')||'<p class="empty-state">Nenhum clã encontrado.</p>';$('clan-directory').querySelectorAll<HTMLButtonElement>('[data-clan-apply]').forEach(b=>b.onclick=()=>void this.mutate('apply',{clan:b.dataset.clanApply},b));this.hub.features.pager('clan-pages',d.page,d.clans.length>20,(p:number)=>void this.directory(p));}
 async mutate(op:string,data:any,b?:HTMLButtonElement){await this.action(async()=>{await this.request('clan/'+op,data);await this.hub.refresh(false);await this.loadClan();},b);}
 async clanChat(){const clan=this.clan?.clan_id,epoch=this.epoch;if(!clan)return;try{const d=await this.request('chat?channel=clan');if(epoch!==this.epoch||clan!==this.clan?.clan_id||!$('clan-messages'))return;const box=$('clan-messages'),bottom=box.scrollHeight-box.scrollTop-box.clientHeight<80;const html=d.messages.map((m:any)=>`<div class="chat-message"><strong>${esc(m.name)}</strong><p>${esc(m.text)}</p></div>`).join('')||'<p>Comece a conversa com seu clã.</p>';if(box.innerHTML!==html){box.innerHTML=html;if(bottom)box.scrollTop=box.scrollHeight;}}catch(e:any){if($('clan-messages'))$('clan-messages').textContent=e.message;}}
 confirm(title:string,copy:string,fn:()=>Promise<any>){const dialog=$('trade-dialog') as HTMLDialogElement;$('trade-content').innerHTML=`<h2>${esc(title)}</h2><p>${esc(copy)}</p><p id="trade-error" role="status"></p><div class="item-actions"><button id="trade-cancel" type="button" class="outline-button">Cancelar</button><button id="trade-confirm" class="primary-button">CONFIRMAR</button></div>`;$('trade-cancel').onclick=()=>dialog.close();($('trade-content') as HTMLFormElement).onsubmit=async e=>{e.preventDefault();const b=$('trade-confirm') as HTMLButtonElement;b.disabled=true;try{await fn();dialog.close();await this.hub.refresh(false);await this.loadClan();}catch(e:any){$('trade-error').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
}
